name: run-tests

on:
  push:
    branches:
      - main
      - 1.x
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [ '14.x', '16.x' ]

    name: Node v${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ maxtrix.node }}
      - run: npm ci
      - run: npm lint
      - run: npm test
      - run: npm build
